/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package uas;

import java.io.IOException;
import javax.swing.JScrollPane;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class RegisterForm extends javax.swing.JPanel {

    /**
     * Creates new form RegisterForm
     
    public static Database instance; 
    private final String DB_TYPE = "mysql"; 
    private final String DB_HOST = "localhost"; 
    private final String DB_PORT = "3306"; 
    private final String DB_NAME = "uas"; 
    private final String DB_USER = "root"; 
    private final String DB_PASS = "";*/
    public final JScrollPane contentScrollPane;
    public RegisterForm(JScrollPane contentScrollPane) {
        initComponents();
        this.contentScrollPane = contentScrollPane;
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jCheckBox1 = new javax.swing.JCheckBox();
        pwdRegister = new javax.swing.JPasswordField();
        konPwdRegister = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        logRegister = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        regRegister1 = new javax.swing.JButton();
        nimRegister = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        kelasRegist = new javax.swing.JTextField();
        namaRegist = new javax.swing.JTextField();

        jCheckBox1.setText("jCheckBox1");

        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(new java.awt.GridBagLayout());

        pwdRegister.setPreferredSize(new java.awt.Dimension(800, 1000));
        pwdRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdRegisterActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 117;
        gridBagConstraints.ipady = -5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 14, 0, 0);
        add(pwdRegister, gridBagConstraints);

        konPwdRegister.setPreferredSize(new java.awt.Dimension(800, 1000));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 117;
        gridBagConstraints.ipady = -5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 14, 0, 0);
        add(konPwdRegister, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Form Registrasi");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(301, 354, 0, 0);
        add(jLabel1, gridBagConstraints);

        jLabel2.setText("NIM");
        jLabel2.setPreferredSize(new java.awt.Dimension(800, 1000));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 344, 0, 0);
        add(jLabel2, gridBagConstraints);

        jLabel3.setText("Password");
        jLabel3.setPreferredSize(new java.awt.Dimension(800, 1000));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 344, 0, 0);
        add(jLabel3, gridBagConstraints);

        jLabel4.setText("Konfirmasi Password");
        jLabel4.setPreferredSize(new java.awt.Dimension(800, 1000));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 344, 0, 0);
        add(jLabel4, gridBagConstraints);

        logRegister.setText("Login");
        logRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logRegisterActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.ipadx = 71;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 7, 0, 0);
        add(logRegister, gridBagConstraints);

        jLabel5.setText("Already have an account?");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.ipadx = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 11, 0, 376);
        add(jLabel5, gridBagConstraints);

        regRegister1.setText("Register");
        regRegister1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regRegister1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.ipadx = 55;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 7, 362, 0);
        add(regRegister1, gridBagConstraints);

        nimRegister.setPreferredSize(new java.awt.Dimension(800, 1000));
        nimRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nimRegisterActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 117;
        gridBagConstraints.ipady = -5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 14, 0, 0);
        add(nimRegister, gridBagConstraints);

        jLabel6.setText("Nama");
        jLabel6.setPreferredSize(new java.awt.Dimension(800, 1000));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(32, 344, 0, 0);
        add(jLabel6, gridBagConstraints);

        jLabel7.setText("Kelas");
        jLabel7.setPreferredSize(new java.awt.Dimension(800, 1000));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 344, 0, 0);
        add(jLabel7, gridBagConstraints);

        kelasRegist.setPreferredSize(new java.awt.Dimension(800, 1000));
        kelasRegist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelasRegistActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 117;
        gridBagConstraints.ipady = -5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 14, 0, 0);
        add(kelasRegist, gridBagConstraints);

        namaRegist.setPreferredSize(new java.awt.Dimension(800, 1000));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 117;
        gridBagConstraints.ipady = -5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(32, 14, 0, 0);
        add(namaRegist, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void pwdRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdRegisterActionPerformed

    private void logRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logRegisterActionPerformed
        // TODO add your handling code here:
        contentScrollPane.setViewportView(new LoginPanel(contentScrollPane));
        
    }//GEN-LAST:event_logRegisterActionPerformed

    private void regRegister1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regRegister1ActionPerformed
        // TODO add your handling code here:
        Mahasiswa mhs = new Mahasiswa();
        //mhs.setNim(nimRegister.getText());
        //mhs.setPassword(pwdRegister.getText());
        
        String nama= namaRegist.getText();
        String kelas = kelasRegist.getText();
        String nim = nimRegister.getText();
        String pwd = pwdRegister.getText();
        String kon = konPwdRegister.getText();
        mhs.setNim(nim);
        mhs.setPassword(pwd);
        mhs.setNama(nama);
        mhs.setKelas(kelas);
        if(kon == null ? pwd == null : kon.equals(pwd)){
            
            try {
                Database.getInstance().registMahasiswa(mhs);
            } catch (SQLException ex) {
                Logger.getLogger(RegisterForm.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(RegisterForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            //clearForm();
            JOptionPane.showMessageDialog(this, "Sukses Tersimpan");
        } else{
            JOptionPane.showMessageDialog(this, "Gagal Menyimpan Data");
        }
        
    }//GEN-LAST:event_regRegister1ActionPerformed

    private void nimRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nimRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nimRegisterActionPerformed

    private void kelasRegistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelasRegistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kelasRegistActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField kelasRegist;
    private javax.swing.JPasswordField konPwdRegister;
    private javax.swing.JButton logRegister;
    private javax.swing.JTextField namaRegist;
    private javax.swing.JTextField nimRegister;
    private javax.swing.JPasswordField pwdRegister;
    private javax.swing.JButton regRegister1;
    // End of variables declaration//GEN-END:variables
}
